cleanup and compatibility enhancements for jessie

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -46,6 +46,8 @@
 # on BPI and RPI and is believe to work on generic Linux installations
 #
 
+downloadpath="https://raw.githubusercontent.com/dbursem/ogn-bootstrap/master/"
+
 progress() {
     echo ""
     echo -e "\033[32m * $1\033[0m"
@@ -60,40 +62,40 @@ echo "starting..."
 sudo="sudo"
 which sudo || {
     if [ `whoami` == 'root' ] ; then
-	sudo () {
-	    $@
-	}
-	sudo=""
-	progress "Not using sudo - running as root"
+    sudo () {
+        $@
+    }
+    sudo=""
+    progress "Not using sudo - running as root"
     else
-	error "Please install sudo or run this script as root"
-	exit 1
+    error "Please install sudo or run this script as root"
+    exit 1
     fi
 }
 
-	
+    
 
 if [ "$1" == "" ] ; then
     progress "Adding ogn user and installing as that"
 
     if [ ! -e /home/ogn ]; then
 
-	sudo useradd -m -G `groups|tr ' ' ,` ogn || {
-	    progress "unable to add ogn user?!"
-	    exit
-	}
+    sudo useradd -m -G `groups|tr ' ' ,` ogn || {
+        progress "unable to add ogn user?!"
+        exit
+    }
 
-	echo "ogn:ogn" | sudo chpasswd
+    echo "ogn:ogn" | sudo chpasswd
 
-	progress "Updating package information"
-	sudo apt-get update
-	
-	progress "Updating install packages"
-	sudo apt-get -y upgrade
+    progress "Updating package information"
+    sudo apt-get update
+    
+    progress "Updating install packages"
+    sudo apt-get -y upgrade
 
     else
 
-	progress "using existing ogn user"
+    progress "using existing ogn user"
 
     fi
 
@@ -116,57 +118,37 @@ upgrade=$2
 if [ "$upgrade" != "1" ] ; then
 
     if [ -e /usr/bin/rpi-update ] ; then
-	progress "Updating Operating System (rpi-update)"
-	rpi-update
-	
-	progress "Blocking unwanted SDR stuff"
-	
-	touch /etc/modprobe.d/rtl-glidernet-blacklist.conf
-	echo "blacklist rtl2832" >> /etc/modprobe.d/rtl-glidernet-blacklist.conf
-	echo "blacklist r820t"  >> /etc/modprobe.d/rtl-glidernet-blacklist.conf
-	echo "blacklist rtl2830"  >> /etc/modprobe.d/rtl-glidernet-blacklist.conf
-	echo "blacklist dvb_usb_rtl28xxu"  >> /etc/modprobe.d/rtl-glidernet-blacklist.conf
-	
-	updated=1
+        progress "Updating Operating System (rpi-update)"
+        rpi-update
+        updated=1
+    elif [ `which do-release-upgrade` != "" ] ; then
+        progress "Updating Operating System (do-release-upgrade)"
+        do-release-upgrade
+        updated=1
+    elif [ `which apt-get` != "" ] ; then
+        progress "Updating Operating System (apt-get)"
+        apt-get update
+        apt-get -y upgrade
+        updated=1
+    else
+        progress "No automatic update available"
     fi
     
-    if [ `which do-release-upgrade` != "" ] ; then
-	
-	progress "Updating Operating System (do-release-upgrade)"
-	do-release-upgrade
-	
-	updated=1
-    fi
 fi
-
 
 ## capture if we are doing online config or not
 online=$1
 
 ## dependencies
 progress "Installing dependencies"
-apt-get -y install git cmake libusb-1.0-0-dev libconfig-dev fftw3-dev libjpeg-dev libconfig9 procserv telnet ntp curl dialog openssl sudo make gcc
+apt-get -y install git cmake libusb-1.0-0-dev libconfig-dev fftw3-dev libjpeg-dev libconfig9 procserv telnet ntp curl dialog openssl sudo make gcc rtl-sdr
 
-progress "Installing rtlsdr"
 cd /home/ogn
-git clone git://git.osmocom.org/rtl-sdr.git
-cd rtl-sdr/
-mkdir build
-cd build
-
-if [ -e /dev/udev ]; then
-    cmake ../ -DCMAKE_INSTALL_PREFIX=/usr -DINSTALL_UDEV_RULES=ON
-else
-    cmake ../ -DCMAKE_INSTALL_PREFIX=/usr
-fi
-
-make
- make install
- ldconfig
-cd ../..
 
 # make sure the mod probe stuff is blocked properly on the pi
-if [ -e /usr/bin/rpi-update ] ; then
+# necessary not only on RPi, and wont hurt anyway
+
+#if [ -e /usr/bin/rpi-update ] ; then
     progress "Blocking unwanted SDR stuff"
     
     touch /etc/modprobe.d/rtl-glidernet-blacklist.conf
@@ -174,25 +156,30 @@ if [ -e /usr/bin/rpi-update ] ; then
     echo "blacklist r820t"  >> /etc/modprobe.d/rtl-glidernet-blacklist.conf
     echo "blacklist rtl2830"  >> /etc/modprobe.d/rtl-glidernet-blacklist.conf
     echo "blacklist dvb_usb_rtl28xxu"  >> /etc/modprobe.d/rtl-glidernet-blacklist.conf
-fi
+    ## I had to add (one of) these lines as well on my OrangePi running Jessie
+    echo "blacklist dvb_usb_rtl2832u"  >> /etc/modprobe.d/rtl-glidernet-blacklist.conf
+    echo "blacklist dvb_usb_rtl2830u"  >> /etc/modprobe.d/rtl-glidernet-blacklist.conf
+#fi
 
 progress "Adding system startup scripts"
- curl 'https://ognconfig.onglide.com/files/v2.0/rtlsdr-ogn' -R -# -o /etc/init.d/rtlsdr-ogn
- curl 'https://ognconfig.onglide.com/files/v2.0/rtlsdr-ogn.conf' -R -# -o /etc/rtlsdr-ogn.conf
+ curl "{$downloadpath}rtlsdr-ogn" -R -# -o /etc/init.d/rtlsdr-ogn
+ curl "{$downloadpath}rtlsdr-ogn.conf" -R -# -o /etc/rtlsdr-ogn.conf
  chmod +x /etc/init.d/rtlsdr-ogn
 
 progress "Installing updater and using it to install RTLSDR"
- curl 'https://ognconfig.onglide.com/files/v2.0/update' -R -# -o /home/ogn/update
- chmod +x /home/ogn/update
- # if we don't have a configuration file then make a dummy one, we also need to make the rtlsdr-ogn
- # symlink or it will get confused
- if [ ! -e /home/ogn/rtlsdr-ogn ] ; then
-     mkdir /home/ogn/rtlsdr-ogn-bootstrap
-     (cd /home/ogn; ln -s rtlsdr-ogn-bootstrap rtlsdr-ogn)
- fi;
- if [ ! -e /home/ogn/rtlsdr-ogn.conf ] ; then 
-     echo "APRS:\n{ Call = \"BootstrapRequired\";\n" > /home/ogn/rtlsdr-ogn.conf
- fi;
+curl "{$downloadpath}update" -R -# -o /home/ogn/update
+chmod +x /home/ogn/update
+ 
+# if we don't have a configuration file then make a dummy one, we also need to make the rtlsdr-ogn
+# symlink or it will get confused
+if [ ! -e /home/ogn/rtlsdr-ogn ] ; then
+    mkdir /home/ogn/rtlsdr-ogn-bootstrap
+    (cd /home/ogn; ln -s rtlsdr-ogn-bootstrap rtlsdr-ogn)
+fi;
+if [ ! -e /home/ogn/rtlsdr-ogn.conf ] ; then 
+    echo "APRS:\n{ Call = \"BootstrapRequired\";\n" > /home/ogn/rtlsdr-ogn.conf
+fi;
+
 # this is until we actually have a file that we can install... we copy the correct one later on
  /home/ogn/update -i
 
@@ -203,38 +190,50 @@ fi;
 
 progress "Adding startup scripts - this will produce warnings about LSB tabs"
 
- curl 'https://ognconfig.onglide.com/files/v2.0/rtlsdr-ogn' -R -# -o /etc/init.d/rtlsdr-ogn
- curl 'https://ognconfig.onglide.com/files/v2.0/rtlsdr-ogn.conf' -R -# -o /etc/rtlsdr-ogn.conf
- chmod +x /etc/init.d/rtlsdr-ogn
- cp rtlsdr-ogn/Template.conf /home/ogn/rtlsdr-ogn.conf
- chown ogn /home/ogn/rtlsdr-ogn.conf
+curl '{$downloadpath}rtlsdr-ogn' -R -# -o /etc/init.d/rtlsdr-ogn
+curl '{$downloadpath}rtlsdr-ogn.conf' -R -# -o /etc/rtlsdr-ogn.conf
+chmod +x /etc/init.d/rtlsdr-ogn
+cp rtlsdr-ogn/Template.conf /home/ogn/rtlsdr-ogn.conf
+chown ogn /home/ogn/rtlsdr-ogn.conf
+if [ -e /etc/systemd ] ; then
+    curl '{$downloadpath}rtlsdr-ogn.service' -R -# -o /etc/systemd/system/rtlsdr-ogn.service
+fi;
 
 if [ "$online" != "1" ] ; then
-     curl 'https://ognconfig.onglide.com/files/v2.0/httpi' -R -# -o /usr/local/bin/httpi
-     curl 'https://ognconfig.onglide.com/files/v2.0/first-install' -R -# -o /etc/init.d/first-install
-     chmod +x /etc/init.d/first-install /usr/local/bin/httpi
-     update-rc.d first-install defaults
-     update-rc.d rtlsdr-ogn remove
-     touch /etc/ssh/ssh_host_keyswrong    
+    curl '{$downloadpath}httpi' -R -# -o /usr/local/bin/httpi
+    curl '{$downloadpath}first-install' -R -# -o /etc/init.d/first-install
+    chmod +x /etc/init.d/first-install /usr/local/bin/httpi
+    ##new systemctl calls
+    if [ -e /etc/systemd ] ; then
+        systemctl enable first-install
+        systemctl disable rtlsdr-ogn.service
+    else
+        update-rc.d first-install defaults
+        update-rc.d rtlsdr-ogn remove
+    fi;
+    touch /etc/ssh/ssh_host_keyswrong    
 
     progress "Done.  Please reboot your device.  You will be able to configure it at https://ognconfig.onglide.com when it reboots"
-    progress "Also, you may wish to update your operating system"
+    #progress "Also, you may wish to update your operating system"
 
     if [ "$updated" != "1" ] ; then
-	error "You may need to upgrade your operating system as well"
+    error "You may need to upgrade your operating system as well"
+    fi
+else
+
+    if [ -e /etc/systemd ] ; then
+        systemctl disable first-install
+        systemctl enable rtlsdr-ogn.service
+    else
+        update-rc.d first-install remove
+        update-rc.d rtlsdr-ogn defaults
+    fi;
+
+    progress "You device is ready for configuration.  Please edit the configuration file: /home/ogn/rtlsdr-ogn.conf"
+    progress "And then reboot"
+
+    if [ $updated != "1" ] ; then
+        error "You may need to upgrade your operating system as well"
     fi
 
-    exit
 fi
-
-update-rc.d rtlsdr-ogn defaults
-update-rc.d first-install remove
-
-progress "You device is ready for configuration.  Please edit the configuration file: /home/ogn/rtlsdr-ogn.conf"
-progress "And then reboot"
-
-if [ $updated != "1" ] ; then
-    error "You may need to upgrade your operating system as well"
-fi
-
-
